name: Build Geode Mod

on:
  workflow_dispatch:
  push:
    branches:
      - '**'

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        config:
        - name: Windows
          os: windows-latest
        - name: Android32
          os: ubuntu-latest
          target: Android32
        - name: Android64
          os: ubuntu-latest
          target: Android64
        - name: macOS
          os: macos-latest
        - name: iOS
          os: macos-latest
          target: iOS
        

    name: ${{ matrix.config.name }}
    runs-on: ${{ matrix.config.os }}

    steps:
      - uses: actions/checkout@v4

      - name: Build the mod (Release)
        uses: geode-sdk/build-geode-mod@main
        with:
          # build-config: RelWithDebInfo
          # export-pdb: true
          # bindings: RayDeeUx/bindings
          # bindings-ref: "foobar"
          combine: true
          target: ${{ matrix.config.target }}
          cli: nightly # remove once iOS finishes
          sdk: nightly # remove once iOS finishes
